services:
  db:
    image: postgres:16
    ports:
      - "5555:5432"             # prerequisites: 5555 port must be free on your machine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
